@ECHO OFF

:: HOME DIRECTORY
SET SRC_HOME=%~dp0
SET SRC_HOME=%SRC_HOME:"=%
SET SRC_HOME=%SRC_HOME:~0,-1%

:: ELECTRON DIRECTORY
SET SRC_ELECTRON=%SRC_HOME%\node_modules\electron\dist\electron.exe

:: APP DIRECTORY
SET SRC_APP=%SRC_HOME%\app


:: EXECUTE ELECTRON
START "TurboPutative" "%SRC_ELECTRON%" "%SRC_APP%"
REM CMD /C " "%SRC_ELECTRON%" "%SRC_APP%" "